services:
  quizzies:
    image: ghcr.io/avirut/quizzies:master
    container_name: quizzies
    restart: unless-stopped
    volumes:
      - ~/selfhosted/data/jellyfin:/config
    ports:
      - 3000:3000