services:
  quizzies:
    image: ghcr.io/avirut/quizzies:master
    container_name: quizzies
    restart: unless-stopped
    volumes:
      - ./quizzies.db:/app/src/lib/server/db/quizzies.db
    ports:
      - 3000:3000